# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a30b35491226060862107c5b124f5ebc68530d744bf181e1e7b01c3b42dd1efb956e99b306adc5ef7ef78190695e0d87bf3eff830643a87955ab1cd1ced4af8

test:
  secret_key_base: e292d366a23c52b9b796cc23ad4608b006cd9bb7b750b3ea955af2145d1a7032513c07148fadeb4f2facc7224db0083c849f3dfb95450416a5295f8430a0b14b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
